image: Visual Studio 2019
configuration: Release
platform: Any CPU
environment:
  JAVA_HOME: '%ProgramFiles%\Java\jdk1.8.0'
  GRADLE_OPTS: '-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false -Dorg.gradle.daemon=false'
  GeneratePackageOnBuild: true
cache:
  - '%ProgramData%\chocolatey\bin -> .appveyor.yml'
  - '%ProgramData%\chocolatey\lib -> .appveyor.yml'
  - DotNet\packages -> DotNet\**\packages.config
  - '%LocalAppData%\NuGet\v3-cache'
  - '%UserProfile%\.gradle\wrapper -> Java\gradle\wrapper\gradle-wrapper.properties'
install:
  - choco install gitversion.portable -pre -y
before_build:
  - cmd: nuget restore DotNet\CesiumLanguageWriter.sln
  - ps: gitversion /l console /output buildserver /updateprojectfiles DotNet
build:
  project: DotNet\CesiumLanguageWriter.sln
  parallel: true
  verbosity: minimal
after_build:
  - ps: |
      gci DotNet\CesiumLanguageWriter\bin\$env:configuration\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      (gc Java\gradle.properties) | % { $_ -replace "^version = .*$", "version = $env:GitVersion_NuGetVersion" } | sc Java\gradle.properties
      .\Java\gradlew.bat -p Java assemble
      gci Java\CesiumLanguageWriter\build\libs\*.jar | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test:
  assemblies:
    - DotNet\CesiumLanguageWriterTests\bin\$(configuration)\CesiumLanguageWriterTests.dll
after_test:
  - ps: |
      7z a ValidationDotNet.zip (gci DotNet -Recurse -Include ValidationDocument.czml,ValidationDocument*.js).FullName
      Push-AppveyorArtifact ValidationDotNet.zip
      .\Java\gradlew.bat -p Java check
      $wc = New-Object System.Net.WebClient
      $url = "https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID"
      gci Java\CesiumLanguageWriterTests\build\test-results\test\*.xml | % { $wc.UploadFile($url, $_) }
      7z a ValidationJava.zip (gci Java -Recurse -Include ValidationDocument.czml,ValidationDocument*.js).FullName
      Push-AppveyorArtifact ValidationJava.zip
